# interfaces.py # NOT USED AT THE MOMENT
from typing import Protocol, runtime_checkable

@runtime_checkable
class InputGenerator(Protocol):
    def generate_tunable_parameters(self,root_cause): ...
    def generate_time_varying_inputs(self, root_cause, uST, stop_time): ...
    def generate_time_varying_parameters(self, mle, root_cause, uST, stop_time): ...